// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzc3gcATtpzRcpF4BfTKPg9fe_O7MvdxM',
    appId: '1:95087496267:web:30ca7921fb133c0fd591ce',
    messagingSenderId: '95087496267',
    projectId: 'quiz2om-131a8',
    authDomain: 'quiz2om-131a8.firebaseapp.com',
    storageBucket: 'quiz2om-131a8.firebasestorage.app',
    measurementId: 'G-PQZ8QCXYEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_Un8ovciLtKX7Gs9jPMw1pCljx5y5f4',
    appId: '1:95087496267:android:c6efb31f1d1b6d9cd591ce',
    messagingSenderId: '95087496267',
    projectId: 'quiz2om-131a8',
    storageBucket: 'quiz2om-131a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAndD1vJ0NMPafVMaASc8HgO68RUeaqpoo',
    appId: '1:95087496267:ios:a754d866533bdd6dd591ce',
    messagingSenderId: '95087496267',
    projectId: 'quiz2om-131a8',
    storageBucket: 'quiz2om-131a8.firebasestorage.app',
    iosBundleId: 'com.example.comQuiz2omApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAndD1vJ0NMPafVMaASc8HgO68RUeaqpoo',
    appId: '1:95087496267:ios:a754d866533bdd6dd591ce',
    messagingSenderId: '95087496267',
    projectId: 'quiz2om-131a8',
    storageBucket: 'quiz2om-131a8.firebasestorage.app',
    iosBundleId: 'com.example.comQuiz2omApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzc3gcATtpzRcpF4BfTKPg9fe_O7MvdxM',
    appId: '1:95087496267:web:9e2fd807f5adb4fed591ce',
    messagingSenderId: '95087496267',
    projectId: 'quiz2om-131a8',
    authDomain: 'quiz2om-131a8.firebaseapp.com',
    storageBucket: 'quiz2om-131a8.firebasestorage.app',
    measurementId: 'G-JPFXXNKKXD',
  );
}
